name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - uses: actions/checkout@v3

      - name: Restore Packages
        run: dotnet restore

      - name: Build app for release (Windows)
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

      - name: Build app for release (Linux)
        run: dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: Exiled.Archiver-win-x64
          path: Exiled.Archiver/bin/Release/net8.0/win-x64/publish/Exiled.Archiver.exe

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: Exiled.Archiver-linux-x64
          path: Exiled.Archiver/bin/Release/net8.0/linux-x64/publish/Exiled.Archiver
